/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LoginId = IDL.Text;
export const HashedPassword = IDL.Text;
export const AuthorizationToken = IDL.Record({
  'loginId' : LoginId,
  'isAdmin' : IDL.Bool,
});
export const Role = IDL.Variant({
  'manager' : IDL.Null,
  'admin' : IDL.Null,
  'operator' : IDL.Null,
});
export const KaizenStatus = IDL.Variant({
  'closed' : IDL.Null,
  'assigned' : IDL.Null,
  'submitted' : IDL.Null,
  'approved' : IDL.Null,
  'implemented' : IDL.Null,
  'rejected' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Time = IDL.Int;
export const Kaizen = IDL.Record({
  'id' : IDL.Text,
  'status' : KaizenStatus,
  'title' : IDL.Text,
  'improvement' : IDL.Text,
  'submitter' : IDL.Principal,
  'lastUpdate' : Time,
  'timestamp' : Time,
  'assignedDepartment' : IDL.Opt(IDL.Text),
  'managerComment' : IDL.Opt(IDL.Text),
  'department' : IDL.Opt(IDL.Text),
  'requiredTools' : IDL.Opt(IDL.Text),
  'benefit' : IDL.Text,
  'problemStatement' : IDL.Text,
});
export const Observation = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'submitter' : IDL.Principal,
  'area' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'obsType' : IDL.Text,
  'timestamp' : Time,
});
export const OperatorProfileActivity = IDL.Record({
  'operator' : IDL.Principal,
  'lastActivity' : Time,
  'name' : IDL.Opt(IDL.Text),
  'role' : IDL.Opt(Role),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const OperatorActivity = IDL.Record({
  'operator' : IDL.Principal,
  'lastActivity' : Time,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Photo = IDL.Record({
  'id' : IDL.Text,
  'kaizenId' : IDL.Text,
  'contentType' : IDL.Text,
  'blob' : ExternalBlob,
  'filename' : IDL.Text,
  'timestamp' : Time,
  'uploader' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveKaizen' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignDepartment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'authorizeAdmin' : IDL.Func(
      [LoginId, HashedPassword],
      [AuthorizationToken],
      ['query'],
    ),
  'createCredentialWithToken' : IDL.Func(
      [AuthorizationToken, LoginId, HashedPassword, Role, IDL.Bool],
      [],
      [],
    ),
  'getAllKaizens' : IDL.Func([], [IDL.Vec(Kaizen)], ['query']),
  'getAllObservations' : IDL.Func([], [IDL.Vec(Observation)], ['query']),
  'getAllOperatorActivity' : IDL.Func(
      [],
      [IDL.Vec(OperatorProfileActivity)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInactiveOperators' : IDL.Func(
      [IDL.Int],
      [IDL.Vec(OperatorActivity)],
      ['query'],
    ),
  'getKaizen' : IDL.Func([IDL.Text], [Kaizen], ['query']),
  'getKaizensByStatus' : IDL.Func([KaizenStatus], [IDL.Vec(Kaizen)], ['query']),
  'getMaintenanceMode' : IDL.Func([], [IDL.Bool], ['query']),
  'getObservation' : IDL.Func([IDL.Text], [Observation], ['query']),
  'getObservationsByDate' : IDL.Func(
      [Time, Time],
      [IDL.Vec(Observation)],
      ['query'],
    ),
  'getObservationsByType' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Observation)],
      ['query'],
    ),
  'getPhotosForKaizen' : IDL.Func([IDL.Text], [IDL.Vec(Photo)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'pingActivity' : IDL.Func([], [], []),
  'rejectKaizen' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'resetPasswordWithToken' : IDL.Func(
      [AuthorizationToken, LoginId, HashedPassword],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setCredentialStatusWithToken' : IDL.Func(
      [AuthorizationToken, LoginId, IDL.Bool],
      [],
      [],
    ),
  'setMaintenanceMode' : IDL.Func([IDL.Bool], [], []),
  'submitKaizen' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'submitObservation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updateKaizenStatus' : IDL.Func([IDL.Text, KaizenStatus], [], []),
  'uploadPhoto' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
      [],
      [],
    ),
  'validateCredentials' : IDL.Func(
      [LoginId, HashedPassword, Role],
      [],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LoginId = IDL.Text;
  const HashedPassword = IDL.Text;
  const AuthorizationToken = IDL.Record({
    'loginId' : LoginId,
    'isAdmin' : IDL.Bool,
  });
  const Role = IDL.Variant({
    'manager' : IDL.Null,
    'admin' : IDL.Null,
    'operator' : IDL.Null,
  });
  const KaizenStatus = IDL.Variant({
    'closed' : IDL.Null,
    'assigned' : IDL.Null,
    'submitted' : IDL.Null,
    'approved' : IDL.Null,
    'implemented' : IDL.Null,
    'rejected' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Time = IDL.Int;
  const Kaizen = IDL.Record({
    'id' : IDL.Text,
    'status' : KaizenStatus,
    'title' : IDL.Text,
    'improvement' : IDL.Text,
    'submitter' : IDL.Principal,
    'lastUpdate' : Time,
    'timestamp' : Time,
    'assignedDepartment' : IDL.Opt(IDL.Text),
    'managerComment' : IDL.Opt(IDL.Text),
    'department' : IDL.Opt(IDL.Text),
    'requiredTools' : IDL.Opt(IDL.Text),
    'benefit' : IDL.Text,
    'problemStatement' : IDL.Text,
  });
  const Observation = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'submitter' : IDL.Principal,
    'area' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'obsType' : IDL.Text,
    'timestamp' : Time,
  });
  const OperatorProfileActivity = IDL.Record({
    'operator' : IDL.Principal,
    'lastActivity' : Time,
    'name' : IDL.Opt(IDL.Text),
    'role' : IDL.Opt(Role),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const OperatorActivity = IDL.Record({
    'operator' : IDL.Principal,
    'lastActivity' : Time,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Photo = IDL.Record({
    'id' : IDL.Text,
    'kaizenId' : IDL.Text,
    'contentType' : IDL.Text,
    'blob' : ExternalBlob,
    'filename' : IDL.Text,
    'timestamp' : Time,
    'uploader' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveKaizen' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignDepartment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'authorizeAdmin' : IDL.Func(
        [LoginId, HashedPassword],
        [AuthorizationToken],
        ['query'],
      ),
    'createCredentialWithToken' : IDL.Func(
        [AuthorizationToken, LoginId, HashedPassword, Role, IDL.Bool],
        [],
        [],
      ),
    'getAllKaizens' : IDL.Func([], [IDL.Vec(Kaizen)], ['query']),
    'getAllObservations' : IDL.Func([], [IDL.Vec(Observation)], ['query']),
    'getAllOperatorActivity' : IDL.Func(
        [],
        [IDL.Vec(OperatorProfileActivity)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInactiveOperators' : IDL.Func(
        [IDL.Int],
        [IDL.Vec(OperatorActivity)],
        ['query'],
      ),
    'getKaizen' : IDL.Func([IDL.Text], [Kaizen], ['query']),
    'getKaizensByStatus' : IDL.Func(
        [KaizenStatus],
        [IDL.Vec(Kaizen)],
        ['query'],
      ),
    'getMaintenanceMode' : IDL.Func([], [IDL.Bool], ['query']),
    'getObservation' : IDL.Func([IDL.Text], [Observation], ['query']),
    'getObservationsByDate' : IDL.Func(
        [Time, Time],
        [IDL.Vec(Observation)],
        ['query'],
      ),
    'getObservationsByType' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Observation)],
        ['query'],
      ),
    'getPhotosForKaizen' : IDL.Func([IDL.Text], [IDL.Vec(Photo)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'pingActivity' : IDL.Func([], [], []),
    'rejectKaizen' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'resetPasswordWithToken' : IDL.Func(
        [AuthorizationToken, LoginId, HashedPassword],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setCredentialStatusWithToken' : IDL.Func(
        [AuthorizationToken, LoginId, IDL.Bool],
        [],
        [],
      ),
    'setMaintenanceMode' : IDL.Func([IDL.Bool], [], []),
    'submitKaizen' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'submitObservation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateKaizenStatus' : IDL.Func([IDL.Text, KaizenStatus], [], []),
    'uploadPhoto' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
        [],
        [],
      ),
    'validateCredentials' : IDL.Func(
        [LoginId, HashedPassword, Role],
        [],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };