/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AuthorizationToken { 'loginId' : LoginId, 'isAdmin' : boolean }
export interface Credential {
  'id' : LoginId,
  'password' : HashedPassword,
  'role' : Role,
  'enabled' : boolean,
}
export type ExternalBlob = Uint8Array;
export type HashedPassword = string;
export interface Kaizen {
  'id' : string,
  'status' : KaizenStatus,
  'title' : string,
  'improvement' : string,
  'submitter' : Principal,
  'lastUpdate' : Time,
  'timestamp' : Time,
  'assignedDepartment' : [] | [string],
  'managerComment' : [] | [string],
  'department' : [] | [string],
  'requiredTools' : [] | [string],
  'benefit' : string,
  'problemStatement' : string,
}
export type KaizenStatus = { 'closed' : null } |
  { 'assigned' : null } |
  { 'submitted' : null } |
  { 'approved' : null } |
  { 'implemented' : null } |
  { 'rejected' : null } |
  { 'inProgress' : null };
export type LoginId = string;
export interface Observation {
  'id' : string,
  'status' : string,
  'title' : string,
  'submitter' : Principal,
  'area' : [] | [string],
  'description' : string,
  'obsType' : string,
  'timestamp' : Time,
}
export interface OperatorActivity {
  'operator' : Principal,
  'lastActivity' : Time,
}
export interface OperatorProfileActivity {
  'operator' : Principal,
  'lastActivity' : Time,
  'name' : [] | [string],
  'role' : [] | [Role],
}
export interface Photo {
  'id' : string,
  'kaizenId' : string,
  'contentType' : string,
  'blob' : ExternalBlob,
  'filename' : string,
  'timestamp' : Time,
  'uploader' : Principal,
}
export type Role = { 'manager' : null } |
  { 'admin' : null } |
  { 'operator' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveKaizen' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignDepartment' : ActorMethod<[string, string, string], undefined>,
  'authorizeAdmin' : ActorMethod<[LoginId, HashedPassword], AuthorizationToken>,
  'createCredentialWithToken' : ActorMethod<
    [AuthorizationToken, LoginId, HashedPassword, Role, boolean],
    undefined
  >,
  'getAllKaizens' : ActorMethod<[], Array<Kaizen>>,
  'getAllObservations' : ActorMethod<[], Array<Observation>>,
  'getAllOperatorActivity' : ActorMethod<[], Array<OperatorProfileActivity>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInactiveOperators' : ActorMethod<[bigint], Array<OperatorActivity>>,
  'getKaizen' : ActorMethod<[string], Kaizen>,
  'getKaizensByStatus' : ActorMethod<[KaizenStatus], Array<Kaizen>>,
  'getMaintenanceMode' : ActorMethod<[], boolean>,
  'getObservation' : ActorMethod<[string], Observation>,
  'getObservationsByDate' : ActorMethod<[Time, Time], Array<Observation>>,
  'getObservationsByType' : ActorMethod<[string], Array<Observation>>,
  'getPhotosForKaizen' : ActorMethod<[string], Array<Photo>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCredentials' : ActorMethod<[AuthorizationToken], Array<Credential>>,
  'pingActivity' : ActorMethod<[], undefined>,
  'rejectKaizen' : ActorMethod<[string, string], undefined>,
  'resetPasswordWithToken' : ActorMethod<
    [AuthorizationToken, LoginId, HashedPassword],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setCredentialStatusWithToken' : ActorMethod<
    [AuthorizationToken, LoginId, boolean],
    undefined
  >,
  'setMaintenanceMode' : ActorMethod<[boolean], undefined>,
  'submitKaizen' : ActorMethod<
    [string, string, string, string, [] | [string]],
    undefined
  >,
  'submitObservation' : ActorMethod<
    [string, string, string, [] | [string]],
    undefined
  >,
  'updateKaizenStatus' : ActorMethod<[string, KaizenStatus], undefined>,
  'uploadPhoto' : ActorMethod<
    [string, string, string, ExternalBlob],
    undefined
  >,
  'validateCredentials' : ActorMethod<
    [LoginId, HashedPassword, Role],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];