/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    name: string;
    role: string;
}
export type Time = bigint;
export interface OperatorProfileActivity {
    operator: Principal;
    lastActivity: Time;
    name?: string;
    role?: Role;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Observation {
    id: string;
    status: string;
    title: string;
    submitter: Principal;
    area?: string;
    description: string;
    obsType: string;
    timestamp: Time;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type HashedPassword = string;
export interface Kaizen {
    id: string;
    status: KaizenStatus;
    title: string;
    improvement: string;
    submitter: Principal;
    lastUpdate: Time;
    timestamp: Time;
    assignedDepartment?: string;
    managerComment?: string;
    department?: string;
    requiredTools?: string;
    benefit: string;
    problemStatement: string;
}
export interface OperatorActivity {
    operator: Principal;
    lastActivity: Time;
}
export type LoginId = string;
export interface AuthorizationToken {
    loginId: LoginId;
    isAdmin: boolean;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Photo {
    id: string;
    kaizenId: string;
    contentType: string;
    blob: ExternalBlob;
    filename: string;
    timestamp: Time;
    uploader: Principal;
}
export enum KaizenStatus {
    closed = "closed",
    assigned = "assigned",
    submitted = "submitted",
    approved = "approved",
    implemented = "implemented",
    rejected = "rejected",
    inProgress = "inProgress"
}
export enum Role {
    manager = "manager",
    admin = "admin",
    operator = "operator"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    approveKaizen(kaizenId: string, comment: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignDepartment(kaizenId: string, department: string, tools: string): Promise<void>;
    authorizeAdmin(loginId: LoginId, password: HashedPassword): Promise<AuthorizationToken>;
    createCredentialWithToken(token: AuthorizationToken, loginId: LoginId, password: HashedPassword, role: Role, enabled: boolean): Promise<void>;
    getAllKaizens(): Promise<Array<Kaizen>>;
    getAllObservations(): Promise<Array<Observation>>;
    getAllOperatorActivity(): Promise<Array<OperatorProfileActivity>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getInactiveOperators(days: bigint): Promise<Array<OperatorActivity>>;
    getKaizen(id: string): Promise<Kaizen>;
    getKaizensByStatus(status: KaizenStatus): Promise<Array<Kaizen>>;
    getMaintenanceMode(): Promise<boolean>;
    getObservation(id: string): Promise<Observation>;
    getObservationsByDate(start: Time, end: Time): Promise<Array<Observation>>;
    getObservationsByType(obsType: string): Promise<Array<Observation>>;
    getPhotosForKaizen(kaizenId: string): Promise<Array<Photo>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    pingActivity(): Promise<void>;
    rejectKaizen(kaizenId: string, reason: string): Promise<void>;
    resetPasswordWithToken(token: AuthorizationToken, loginId: LoginId, newPassword: HashedPassword): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setCredentialStatusWithToken(token: AuthorizationToken, loginId: LoginId, enabled: boolean): Promise<void>;
    setMaintenanceMode(enabled: boolean): Promise<void>;
    submitKaizen(title: string, problemStatement: string, improvement: string, benefit: string, department: string | null): Promise<void>;
    submitObservation(obsType: string, title: string, description: string, area: string | null): Promise<void>;
    updateKaizenStatus(kaizenId: string, newStatus: KaizenStatus): Promise<void>;
    uploadPhoto(kaizenId: string, filename: string, contentType: string, blob: ExternalBlob): Promise<void>;
    validateCredentials(loginId: LoginId, password: HashedPassword, selectedRole: Role): Promise<void>;
}
import type { ExternalBlob as _ExternalBlob, Kaizen as _Kaizen, KaizenStatus as _KaizenStatus, Observation as _Observation, OperatorProfileActivity as _OperatorProfileActivity, Photo as _Photo, Role as _Role, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async approveKaizen(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveKaizen(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveKaizen(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignDepartment(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignDepartment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignDepartment(arg0, arg1, arg2);
            return result;
        }
    }
    async authorizeAdmin(arg0: LoginId, arg1: HashedPassword): Promise<AuthorizationToken> {
        if (this.processError) {
            try {
                const result = await this.actor.authorizeAdmin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.authorizeAdmin(arg0, arg1);
            return result;
        }
    }
    async createCredentialWithToken(arg0: AuthorizationToken, arg1: LoginId, arg2: HashedPassword, arg3: Role, arg4: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCredentialWithToken(arg0, arg1, arg2, to_candid_Role_n10(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCredentialWithToken(arg0, arg1, arg2, to_candid_Role_n10(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async getAllKaizens(): Promise<Array<Kaizen>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllKaizens();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllKaizens();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllObservations(): Promise<Array<Observation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllObservations();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllObservations();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllOperatorActivity(): Promise<Array<OperatorProfileActivity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOperatorActivity();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOperatorActivity();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInactiveOperators(arg0: bigint): Promise<Array<OperatorActivity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInactiveOperators(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInactiveOperators(arg0);
            return result;
        }
    }
    async getKaizen(arg0: string): Promise<Kaizen> {
        if (this.processError) {
            try {
                const result = await this.actor.getKaizen(arg0);
                return from_candid_Kaizen_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKaizen(arg0);
            return from_candid_Kaizen_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getKaizensByStatus(arg0: KaizenStatus): Promise<Array<Kaizen>> {
        if (this.processError) {
            try {
                const result = await this.actor.getKaizensByStatus(to_candid_KaizenStatus_n30(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKaizensByStatus(to_candid_KaizenStatus_n30(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMaintenanceMode(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getMaintenanceMode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMaintenanceMode();
            return result;
        }
    }
    async getObservation(arg0: string): Promise<Observation> {
        if (this.processError) {
            try {
                const result = await this.actor.getObservation(arg0);
                return from_candid_Observation_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getObservation(arg0);
            return from_candid_Observation_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getObservationsByDate(arg0: Time, arg1: Time): Promise<Array<Observation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getObservationsByDate(arg0, arg1);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getObservationsByDate(arg0, arg1);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getObservationsByType(arg0: string): Promise<Array<Observation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getObservationsByType(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getObservationsByType(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPhotosForKaizen(arg0: string): Promise<Array<Photo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPhotosForKaizen(arg0);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPhotosForKaizen(arg0);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async pingActivity(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.pingActivity();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pingActivity();
            return result;
        }
    }
    async rejectKaizen(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectKaizen(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectKaizen(arg0, arg1);
            return result;
        }
    }
    async resetPasswordWithToken(arg0: AuthorizationToken, arg1: LoginId, arg2: HashedPassword): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetPasswordWithToken(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetPasswordWithToken(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setCredentialStatusWithToken(arg0: AuthorizationToken, arg1: LoginId, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setCredentialStatusWithToken(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCredentialStatusWithToken(arg0, arg1, arg2);
            return result;
        }
    }
    async setMaintenanceMode(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMaintenanceMode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMaintenanceMode(arg0);
            return result;
        }
    }
    async submitKaizen(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitKaizen(arg0, arg1, arg2, arg3, to_candid_opt_n36(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitKaizen(arg0, arg1, arg2, arg3, to_candid_opt_n36(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async submitObservation(arg0: string, arg1: string, arg2: string, arg3: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitObservation(arg0, arg1, arg2, to_candid_opt_n36(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitObservation(arg0, arg1, arg2, to_candid_opt_n36(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateKaizenStatus(arg0: string, arg1: KaizenStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateKaizenStatus(arg0, to_candid_KaizenStatus_n30(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateKaizenStatus(arg0, to_candid_KaizenStatus_n30(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async uploadPhoto(arg0: string, arg1: string, arg2: string, arg3: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadPhoto(arg0, arg1, arg2, await to_candid_ExternalBlob_n37(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadPhoto(arg0, arg1, arg2, await to_candid_ExternalBlob_n37(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async validateCredentials(arg0: LoginId, arg1: HashedPassword, arg2: Role): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.validateCredentials(arg0, arg1, to_candid_Role_n10(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateCredentials(arg0, arg1, to_candid_Role_n10(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_KaizenStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KaizenStatus): KaizenStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Kaizen_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Kaizen): Kaizen {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Observation_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Observation): Observation {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_OperatorProfileActivity_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OperatorProfileActivity): OperatorProfileActivity {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
async function from_candid_Photo_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Photo): Promise<Photo> {
    return await from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Role]): Role | null {
    return value.length === 0 ? null : from_candid_Role_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _KaizenStatus;
    title: string;
    improvement: string;
    submitter: Principal;
    lastUpdate: _Time;
    timestamp: _Time;
    assignedDepartment: [] | [string];
    managerComment: [] | [string];
    department: [] | [string];
    requiredTools: [] | [string];
    benefit: string;
    problemStatement: string;
}): {
    id: string;
    status: KaizenStatus;
    title: string;
    improvement: string;
    submitter: Principal;
    lastUpdate: Time;
    timestamp: Time;
    assignedDepartment?: string;
    managerComment?: string;
    department?: string;
    requiredTools?: string;
    benefit: string;
    problemStatement: string;
} {
    return {
        id: value.id,
        status: from_candid_KaizenStatus_n15(_uploadFile, _downloadFile, value.status),
        title: value.title,
        improvement: value.improvement,
        submitter: value.submitter,
        lastUpdate: value.lastUpdate,
        timestamp: value.timestamp,
        assignedDepartment: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.assignedDepartment)),
        managerComment: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.managerComment)),
        department: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.department)),
        requiredTools: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.requiredTools)),
        benefit: value.benefit,
        problemStatement: value.problemStatement
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    title: string;
    submitter: Principal;
    area: [] | [string];
    description: string;
    obsType: string;
    timestamp: _Time;
}): {
    id: string;
    status: string;
    title: string;
    submitter: Principal;
    area?: string;
    description: string;
    obsType: string;
    timestamp: Time;
} {
    return {
        id: value.id,
        status: value.status,
        title: value.title,
        submitter: value.submitter,
        area: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.area)),
        description: value.description,
        obsType: value.obsType,
        timestamp: value.timestamp
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    operator: Principal;
    lastActivity: _Time;
    name: [] | [string];
    role: [] | [_Role];
}): {
    operator: Principal;
    lastActivity: Time;
    name?: string;
    role?: Role;
} {
    return {
        operator: value.operator,
        lastActivity: value.lastActivity,
        name: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.name)),
        role: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.role))
    };
}
async function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    kaizenId: string;
    contentType: string;
    blob: _ExternalBlob;
    filename: string;
    timestamp: _Time;
    uploader: Principal;
}): Promise<{
    id: string;
    kaizenId: string;
    contentType: string;
    blob: ExternalBlob;
    filename: string;
    timestamp: Time;
    uploader: Principal;
}> {
    return {
        id: value.id,
        kaizenId: value.kaizenId,
        contentType: value.contentType,
        blob: await from_candid_ExternalBlob_n35(_uploadFile, _downloadFile, value.blob),
        filename: value.filename,
        timestamp: value.timestamp,
        uploader: value.uploader
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    assigned: null;
} | {
    submitted: null;
} | {
    approved: null;
} | {
    implemented: null;
} | {
    rejected: null;
} | {
    inProgress: null;
}): KaizenStatus {
    return "closed" in value ? KaizenStatus.closed : "assigned" in value ? KaizenStatus.assigned : "submitted" in value ? KaizenStatus.submitted : "approved" in value ? KaizenStatus.approved : "implemented" in value ? KaizenStatus.implemented : "rejected" in value ? KaizenStatus.rejected : "inProgress" in value ? KaizenStatus.inProgress : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    manager: null;
} | {
    admin: null;
} | {
    operator: null;
}): Role {
    return "manager" in value ? Role.manager : "admin" in value ? Role.admin : "operator" in value ? Role.operator : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Kaizen>): Array<Kaizen> {
    return value.map((x)=>from_candid_Kaizen_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Observation>): Array<Observation> {
    return value.map((x)=>from_candid_Observation_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OperatorProfileActivity>): Array<OperatorProfileActivity> {
    return value.map((x)=>from_candid_OperatorProfileActivity_n22(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Photo>): Promise<Array<Photo>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Photo_n33(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_KaizenStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: KaizenStatus): _KaizenStatus {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    manager: null;
} | {
    admin: null;
} | {
    operator: null;
} {
    return value == Role.manager ? {
        manager: null
    } : value == Role.admin ? {
        admin: null
    } : value == Role.operator ? {
        operator: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: KaizenStatus): {
    closed: null;
} | {
    assigned: null;
} | {
    submitted: null;
} | {
    approved: null;
} | {
    implemented: null;
} | {
    rejected: null;
} | {
    inProgress: null;
} {
    return value == KaizenStatus.closed ? {
        closed: null
    } : value == KaizenStatus.assigned ? {
        assigned: null
    } : value == KaizenStatus.submitted ? {
        submitted: null
    } : value == KaizenStatus.approved ? {
        approved: null
    } : value == KaizenStatus.implemented ? {
        implemented: null
    } : value == KaizenStatus.rejected ? {
        rejected: null
    } : value == KaizenStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
